### PR TITLE
note exception to 1-ZST-are-ignored rule

### PR DESCRIPTION
**Pull request by RalfJung**
This is based on what @eddyb [wrote here](https://github.com/rust-lang/rust/pull/73453#issuecomment-674310011).

### CODE REVIEW

**Comment by eddyb** [comment]
I'd hold off on merging this, as at least for the call ABI we could have 1-ZST independence, as per the second half of https://github.com/rust-lang/rust/pull/73453#issuecomment-674310011.

IMO it's more important to point out that ZST fields *still have offsets*, but we don't guarantee anything about them.
(except when field order is guaranteed, I guess? or is `last_field: [T; 0]` a really bad idea?)

**Comment by RalfJung** [comment]
Of course they still have offsets, all fields do.

> The degrees of freedom the compiler has when computing the layout of an inhabited struct or tuple is to determine the order of the fields, and the "gaps" (often called padding) before, between, and after the fields. The layout of these fields themselves is already entirely determined by their types, and since we intend to allow creating references to fields (&s.f1), structs do not have any wiggle-room there.

**Comment by eddyb** [comment]
Can this be closed once https://github.com/rust-lang/rust/pull/73453 lands? @erikdesjardins switched the PR over to fix codegen instead.

**Comment by RalfJung** [comment]
If that lifts the unsizing restriction, then yes, we won't need this docs change any more :)

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/73453 landed so let's close this.

**Pull request closed without merging**
